### ISSUE TITLE
[Bug]: Failed docker compose

### ISSUE THREAD

**Issue by BulldozerPete** [actualbudget/actual-server#326] opened 2024-03-21 19:27 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Hallo,

I can't setup a docker container with the provided docker compose.yml: https://github.com/actualbudget/actual-server/blob/master/docker-compose.yml

Portainer shows me this error: 
<img width="509" alt="photo" src="https://github.com/actualbudget/actual-server/assets/61943052/aab71a1f-e981-4ff8-bd00-c08b31f71982">
Other containers work fine. What is wrong here?

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by MatissJanis** [comment] 2024-03-21 19:28
👋 We don't use Github issues for tech support. Please reach out to the community in the community discord. I'm sure someone will help you there.

Closing as this is not a bug report.

**Comment by youngcw** [comment] 2024-03-21 19:29
If you haven't enabled any of the environment variables it wont work.  Try just enabling the data sync size ones.

**Closed by MatissJanis** 2024-03-21 19:28 UTC
Labels: bug

**Comment by BulldozerPete** [comment] 2024-03-21 19:59
I don't understand.

**Comment by letshin** [comment] 2024-03-26 23:39
Comment out line 9 in the docker compose. `    environment:
`

**Comment by BulldozerPete** [comment] 2024-03-27 10:17
Done. Container now starts but webpage won't load.
