### ISSUE TITLE
[Bug]: Actual docker won't start

### ISSUE THREAD

**Issue by BulldozerPete** [actualbudget/actual-server#327] opened 2024-03-24 11:43 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Hallo,

I have successfully set up a docker container with actual, but it won't load the webpage:
<img width="455" alt="loading" src="https://github.com/actualbudget/actual-server/assets/61943052/4d3da2c7-8680-4512-8fd2-04edcbb6338c">

### What error did you receive?

All the time.

My docker compose:

"version: '3.3'

services:

    actual-server:
        image: actualbudget/actual-server:latest   
        container_name: actualbudget       
        restart: unless-stopped
        ports:
            - '8200:5006'
        volumes:
            - ./actual-data:/data"

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by MatissJanis** [comment] 2024-03-26 18:24
👋 Github issues is not a great spot for tech support. The community is quite active on Discord. Please reach out there.

Closing as this is not a bug report.

**Closed by MatissJanis** 2024-03-26 18:24 UTC
Labels: bug
