### ISSUE TITLE
[Bug]: Link Your Bank (Go Cardless > Ireland > Permanent TSB) results in 500 Server Error - "An error occurred while linking your account, sorry!"

### ISSUE THREAD

**Issue by getoffmyplane** [actualbudget/actual-server#321] opened 2024-03-08 14:02 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The latest version of Actual Budget (which updated the GoCardless API endpoints to the new ones) require my accounts to be relinked via GoCardless.

I use two banks in Ireland - Allied Irish Banks and Permanent TSB.

Allied Irish Banks works fine.

Trying to link my bank account (Country Ireland, Bank Permanent TSB) via GoCardless (on the "Link Your Bank" popup) causes the following error:
500 Server Error - "An error occurred while linking your account, sorry!"

To note:

This error was there before the API endpoints were changed in the latest version of Actual Budget but I was able to work around it by selecting a different bank from the "Link Your Bank" popup, and then updating the institution id in the url on the subsequent browser screen (the Gocardless auth screen).

I got the institution ID from https://docs.google.com/spreadsheets/d/1EZ5n7QDGaRIot5M86dwqd5UFSGEDTeTRzEq3D9uEDkM (which is linked to from the gocardless support section).

Unfortunately, that workaround no longer works (the tab just closes when you press the "agree and accept" button after you change the institution id part of the url).

I checked the response from get-banks (fired by the "Link Your Bank" popup) with Firefox inspect and the response seems to match what is in the spreadsheet

Actual Budget is running in Docker on Ubuntu Server.
I've tried Firefox and Chrome on Windows 11, Fedora 39 & Debian 12 - all return same error.

If I can provide any more info, please let me know.

Thanks!

### What error did you receive?

500 Server Error - "An error occurred while linking your account, sorry!"

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 11

**Comment by getoffmyplane** [comment] 2024-03-15 22:53
Hi again,

I think this may just be that max_historical_days is set to 90 when the max the bank supports, according to GoCardless' spreadsheet, is 89 (go to https://docs.google.com/spreadsheets/d/1EZ5n7QDGaRIot5M86dwqd5UFSGEDTeTRzEq3D9uEDkM, then search "Permanent TSB", then see column D).

Would really appreciate a steer (a bit out of my depth) - if there's somewhere i can update this myself, more than happy to do it.

Thanks!

**Comment by mickotoole02** [comment] 2024-03-20 20:29
Hi @getoffmyplane,

I was having the same problem as you and thanks to you post above I was able to figure out how to get PTSB to sync with Actual. You were spot on the money regarding the maxHistoricalDays being set incorrectly.

I searched for all files that had that set to 90 and manually changed it to 89. Once I did that I was able to connect my account.

$ grep -Ril "maxHistoric" /path/to/actual-server/
/actual-server/src/app-gocardless/services/gocardless-service.js
/actual-server/node_modules/nordigen-node/dist/types/api/agreements.d.ts
/actual-server/node_modules/nordigen-node/dist/types/index.d.ts
/actual-server/node_modules/nordigen-node/dist/index.cjs
/actual-server/node_modules/nordigen-node/dist/index.cjs.map
/actual-server/node_modules/nordigen-node/dist/index.esm.js.map
/actual-server/node_modules/nordigen-node/dist/index.esm.js

In each of these files anywhere I spotted maxHistoricalDays and the number 90 I changed it to 89, saved the file and restarted actual. I'm not sure if every file needed to be changed or not but that's what I did. Hope it works out for you.

**Comment by MatissJanis** [comment] 2024-03-21 19:34
👋 Would you mind sending this bug report directly to GoCardless? I'm sure they can (and should) force the max historical days configuration option to 89 if it's >90 for PTSB.

On Actual side - we do get a 500 error from GoCardless. Obviously it is possible to work around this by changing 90 -> 89, but the root cause is still with GoCardless. So I much prefer if they fix it on their end.

**Comment by koershov** [comment] 2024-03-22 12:48
There are banks that support more than 90 days actually. So could you maybe add it as a parameter when creating a requisition for sync?

**Comment by MatissJanis** [comment] 2024-03-22 18:59
I would not be opposed to an ability to configure `max_historical_days` for users that **know** what they are doing. However, for most users this is not an option we would advertise. The bank-sync should work out-of-the-box without the need to tweak this. I.e. the user should not know that PSTB has to be configured to exactly 89 days as opposed to the default of 90. So even though the `max_historical_days` configurability would be a nice extra addition - it would not solve the PTSB issue reported here. That would still be on GoCardless, so my recommendation there stands - reaching out to GoCardless to report the issue is the best course of action.

**Comment by kesot** [comment] 2024-03-24 08:53
Depend on what they return in GET institutions endpoint as transaction_total_days, that's the max value supported by the bank. If its 89 for PSTB you should respect it. 
Even if they fix the bug and you will get 400 instead of 500 it won't solve the users' issue.

**Comment by MatissJanis** [comment] 2024-03-24 15:47
Lets first report the issue to GoCardless and see what they say. They have a very responsive support and their tech team seems to be very capable. Once the 500 is patched on their end we can discuss next steps (if any).

**Comment by MatissJanis** [comment] 2024-05-05 18:32
The patch has been released in v24.5.0

Thanks @kyrias

**Closed by MatissJanis** 2024-05-05 18:32 UTC
Labels: bug
