### ISSUE TITLE
Accounts get mixed up when syncing multiple files

### ISSUE THREAD

**Issue by juriroemer** [actualbudget/actual-server#15] opened 2022-04-30 16:04 UTC
Steps to reproduce:

1. create file 1, add some accounts, close file 1
2. create file 2, add some accounts, close file 2
3. open file 1: file 1 now only shows the accounts that are defined in file 2
4. close file 1, open file 2: file 2 still shows the accounts defined in file 2, but shows the name of file 1 in the upper left corner

5. close file 2, "delete file 2 locally", "delete file 2 from all devices",  "clear site data" in Chrome dev tools
6. login to actual again
7. open file 1: file 1 now shows ALL accounts from file 1 and the deleted file 2, upper left corner still shows the name of deleted file 2

OS: macOS 12.3.1 on arm64
Browser: Google Chrome v100.0.4896.127 and v101.0.4951.41

**Comment by jlongster** [comment] 2022-05-03 03:38
OH I KNOW WHAT THIS IS

Sorry... there's something wrong at the root of several issues, so I'll write a quick post and point all the questions there

**Comment by slater1** [comment] 2022-05-20 04:00
How is the fix for this coming along? I'm making paranoid backups with the fear that everything could get wiped with a misclick.

**Comment by cristianbostan** [comment] 2022-07-07 18:30
An update on my experience with this issue:
When it happened to me, I was using actual in a docker container.
I tried to deploy it on fly.io and the issue didn't show up any more. Whatever this is, it has to do with the docker image build.

**Closed** 2022-07-07 22:22 UTC

**Comment by dlip** [comment] 2022-07-09 12:18
I'm actually having this same issue still. It seems to only happen when I run using a domain name behind and nginx proxy, if i run it directly on localhost:5006 it seems to be ok. Any ideas?

**Comment by jatls** [comment] 2022-07-09 12:21
> I'm actually having this same issue still. It seems to only happen when I run using a domain name behind and nginx proxy, if i run it directly on localhost:5006 it seems to be ok. Any ideas?

Check your headers are passed through the reverse proxy correctly. It sounds like you have an issue with the nginx proxy, not actual server.

**Comment by dlip** [comment] 2022-07-09 13:01
I was able to reproduce it without nginx by accessing the server through the lan ip (http://10.10.0.114:5006) rather than localhost. I deleted server files, and reset browser cache to be sure. I import my ynab budget, then switch back to the default budget and it has been taken over by my ynab budget.

**Comment by Bostrolicious** [comment] 2022-10-30 08:11
> I was able to reproduce it without nginx by accessing the server through the lan ip (http://10.10.0.114:5006) rather than localhost. I deleted server files, and reset browser cache to be sure. I import my ynab budget, then switch back to the default budget and it has been taken over by my ynab budget.

I'm seeing essentially the same thing now on v22.10.25. I'm only trying to use Actual on my LAN, so I haven't set up nginx. Any time I access Actual through the LAN IP, whether it's running on the same machine or another one, files are no longer independent. If I create two files, add accounts and transactions to each, then close them and reopen them, both files will have all entries. The same thing doesn't happen when accessing the server through localhost.

**Comment by jb-delafosse** [comment] 2023-01-05 14:57
Hey. I had the same issue and got the root cause which is arguably not actual.

To work, actual is using `SharedArrayBuffer` conjointly with HTTP headers (`Cross-Origin-Opener-Policy` and `Cross-Origin-Embedder-Policy` )

When using Actual in Local Network via HTTP, your browser is dropping those headers because it thinks it is unsafe.
It prevent "SharedArrayBuffer" from being used.

![image](https://user-images.githubusercontent.com/19969519/210809644-bcfb63f5-3ce9-4a58-94b2-9eb3ab81189c.png)

Using a reverse proxy in HTTPs should fix the issue.

**Comment by TechwizEE** [comment] 2023-01-12 15:46
I debugged this exact issue and found using a reverse proxy enabling HTTPS fixed it. I documented my work here https://github.com/actualbudget/actual/issues/436.  I also saw the COOP header error show in the post just above when I used HTTP using the host's IP address or URL (i.e. not localhost). 

In my digging I found this post to be helpful: https://github.com/jlongster/absurd-sql/issues/14#issuecomment-902116794

Here is the NGINX `.conf` file I'm using:
```
#ssl on;  # deprecated, use ssl parameter on the listen directive
ssl_session_cache  builtin:1000  shared:SSL:10m;
ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
ssl_prefer_server_ciphers on;

proxy_read_timeout 90;

# Redirect from HTTP to HTTPS
server {
    listen 80;          # Listen for all traffic on port 80
    server_name _;      # Matches any hostname
    return 301 https://$host$request_uri;   # 301 tells browser this is a permanent redirect and specifies the HTTPS version of the original request on port 80
}

server {
    listen 443 ssl;
    server_name <full_URL>;

    ssl_certificate         /etc/nginx/certs/<full_URL>.cert-chain.pem;
    ssl_certificate_key     /etc/nginx/certs/<full_URL>.com.key.pem;

    location / {
        proxy_pass http://actualserver:5006/;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
