### ISSUE TITLE
[Bug]: Unable to Sync account

### ISSUE THREAD

**Issue by nelsongraca** [actualbudget/actual-server#338] opened 2024-04-11 18:39 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Account stoppped syncing through GoCardless, I keep getting the error saying it's not linked properly to link again. Which I already did, twice, I don't see errors in the logs, only the following:

    Available (first 10) transactions properties for new integration of institution in sortTransactions function
    balances: '[{"balanceAmount":{"currency":"EUR","amoun......
    top10SortedTransactions: '[{"transactionId"....

I truncated the actual data for privacy

### What error did you receive?

Account “ACCOUNT_NAME” is not linked properly. Please link it again

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

**Comment by MatissJanis** [comment] 2024-04-13 11:55
👋 Please reach out to the community on the community discord. Closing this issue as it is not a bug report, but rather technical support request.

**Closed by MatissJanis** 2024-04-13 11:55 UTC
Labels: bug
