### ISSUE TITLE
Adapting actual-server to mobile

### ISSUE THREAD

**Issue by EFLql** [actualbudget/actual-server#25] opened 2022-05-04 03:07 UTC
It looks terrible on mobile, Please get some hands to fix that.

**Comment by fuzzmz** [comment] 2022-05-06 13:11
I think this can be considered a duplicate of actualbudget/actual#34

**Comment by RichInSQL** [comment] 2022-08-02 07:03
This is being worked on here - https://github.com/actualbudget/actual/pull/79

**Comment by rich-howell** [comment] 2022-10-28 18:42
Hey @EFLql 

This is currently being developed in https://github.com/actualbudget/actual/pull/79 so I am going to go ahead and close this issue. 

Cheers
Rich

**Closed by rich-howell** 2022-10-28 18:42 UTC
